name: Automation_code_test
on:
  push:
    branches: [ "main" ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Environment Setup
        run: |
          sudo apt-get update
          source .github/customs/envs
          sudo apt-get install cmake build-essential
      - name: test_cmake
        run: cmake .
#    self_test:
#      runs-on: ubuntu-latest
      # 准备执行脚本完整性检测